name: CryptoMarket
version: 1.1.0
description: Cryptocurrency market simulator
author: Evirth
main: main.java.pl.csrv.divinecraft.evirth.cryptomarket.CryptoMarket

commands:
  cryptomarket:
    description: Type '/cryptomarket help' to get more information.
    aliases: [cm]
    usage: /cm help

permission:
  cryptomarket.*:
    description: Gives access to all CryptoMarket commands
    children:
      cryptomarket.player: true
      cryptomarket.admin: true

  cryptomarket.player:
    description: Gives access to player's CryptoMarket commands

  cryptomarket.admin:
    description: Gives access to admin's CryptoMarket commands
    children:
      cryptomarket.balance.others: true
      cryptomarket.history.others: true
      cryptomarket.stats.others: true

  cryptomarket.balance.others:
    description: Gives access to '/cm balance <player>' command

  cryptomarket.history.others:
    description: Gives access to '/cm history <player>' command

  cryptomarket.stats.others:
    description: Gives access to '/cm stats <player>' command
